# Generated by cmake2bazel.
# Any issue please report to https://open.codehub.huawei.com/innersource/hazel/toolkits/issues
# Caesar Task Force@Data Storage Product Line
GLOBAL_COPTS = [
    "-std=gnu++17",
    "-Wunused-variable",
    "-Wunused-value",
    "-Wcast-align",
    "-fpermissive",
    "-Wno-error",
    "-Wcast-qual",
    "-Winvalid-pch",
    "-Wwrite-strings",
    "-Wsign-compare",
    "-Wfloat-equal",
    "-Wextra",
    "-Wno-deprecated-declarations",
] + select({
    "//:memfabric_mode_dbg": [
        "-g",
        "-ggdb3",
        "-O0",
        "-fno-omit-frame-pointer",
        "-rdynamic",
        "-fPIC",
    ],
    "//conditions:default": [],
}) + select({
    "//:memfabric_mode_opt": [
        "-fstack-protector-strong",
        "-Wstack-usage=16384",
        "-Werror",
        "-Wl,-z,noexecstack",
        "-Wl,-z,relro",
        "-Wl,-z,now",
        "-fPIE",
        "-fPIC",
        "-ftrapv",
        "-s",
        "-D_FORTIFY_SOURCE=2",
        "-O2",
    ],
    "//conditions:default": [],
})

GLOBAL_LINKOPTS = [] + select({
    "//:memfabric_mode_dbg": [
        "-rdynamic",
    ],
    "//conditions:default": [],
}) + select({
    "//:memfabric_mode_opt": [
        "-Wl,-z,noexecstack,-z,relro,-z,now",
        "-s",
    ],
    "//conditions:default": [],
})

GLOBAL_LOCAL_DEFINES = []