# Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
# MemFabric_Hybrid is licensed under Mulan PSL v2.

load("//bazel:global_options.bzl", "GLOBAL_COPTS", "GLOBAL_LOCAL_DEFINES", "GLOBAL_LINKOPTS")
load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")

package(default_visibility = ["//visibility:private"])

COMMON_LINKOPTS = GLOBAL_LINKOPTS + []

COMMON_LOCAL_DEFINES = GLOBAL_LOCAL_DEFINES + ["_GLIBCXX_USE_CXX11_ABI=0"]

COMMON_COPTS = GLOBAL_COPTS + [
    "-fabi-version=0",
    "-Isrc/acc_offload/include/host",
    "-Isrc/acc_offload/csrc",
    "-Isrc/acc_offload/csrc/common",
    "-Isrc/acc_offload/csrc/allocator",
    "-Isrc/acc_offload/csrc/launch",
    "-Isrc/acc_offload/csrc/operators",
    "-Isrc/hybm/include",
    "-Isrc/util/csrc/ptracer/include",
    "-Isrc/acc_links/include",
]

pybind_extension(
    name = "_pymf_acc_offload",
    srcs = [
        "pymf_acc_offload.cpp",
    ],
    local_defines = [] + COMMON_LOCAL_DEFINES,
    copts = [] + COMMON_COPTS,
    linkopts = [
        "-Wl,-z,noexecstack,-z,relro,-z,now",
        "-s",
        "-Wl,--start-group",
        "-lrt",
        "-Wl,--end-group",
        "-lpthread",
        "-ldl",
    ] + COMMON_LINKOPTS,
    deps = [
        "//src/acc_links/csrc:acc_tcp_net_static",
        "//src/smem/csrc/config_store:config_store_object",
        "//src/hybm/csrc:hybmm_shared",
        "//src/acc_offload/csrc:acc_offload_shared",
    ],
)
